name: glass_shimmer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.0-147.0.dev
  flutter: 3.22.0-31.0.pre.20

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  leancode_hooks: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.1.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/shimmer.frag
