name: glass_shimmer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.1.0

flutter:
  uses-material-design: true
