name: glass_shimmer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.9.0-172.0.dev
  flutter: 3.33.0-1.0.pre.305

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
  leancode_hooks: ^0.1.1

dev_dependencies:
  leancode_lint: ^16.0.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/border.frag
    - shaders/blur.frag
    - shaders/pillow_rect.frag
    - shaders/sphere.frag
