name: glass_shimmer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.7.0-183.0.dev
  flutter: 3.27.0-1.0.pre.625

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3
  leancode_hooks: ^0.0.6

dev_dependencies:
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/border.frag
    - shaders/blur.frag
    - shaders/pillow_rect.frag
    - shaders/sphere.frag
